### ISSUE TITLE
Number of MoPs

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#11]
In the Google Drive folder, the number of MoPs is [sometimes] specified with the property `P90 has value`, while others `U1.1 has quantity`.

The latter is not better described in ontology or modelling group documents.
So should we use the first one?

(see also #10)

**Comment by pierrechoffe** [comment]
@pasqLisena the "has_quantity" property does not exist, although I wish it would (see my previous message about merging M23 & M35), so the only way we can describe the number of MoPs intended by the composer is p90_has_value.
Is there any way we can describe a quantity in RDF?

**Comment by pasqLisena** [comment]
> see my previous message about merging M23 & M35

Yes, definitively it is better discuss it on #10 .

**Comment by rtroncy** [comment]
There is no RDF built-in property for counting things if this is your question. But, nothing prevent us to create a property for this. Consequently, the ```p90_has_value``` is certainly not the only way of expressing this information and this specific property will be quite badly labeled for this purpose.
