### ISSUE TITLE
Succession properties (U24, U25)

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#16]
In the latest version on the ontology we created 2 new properties:
- `mus:U24_has_successor_in_order`
- `mus:U25_has_successor_in_time`

Both of them are subclass of `ecrm:P130_shows_features_of`, in the same way `efrbroo:R1_is_logical_successor_of` is.

Topic of discussion about these 2 properties:

1. `ecrm:P130_shows_features_of` speaks about [_similarity_](http://erlangen-crm.org/docs/ecrm/111122/objectproperties/P130showsfeaturesof___1040905516.html). We have not this concept in chronological/numerical succession. However, this could apply also to the `frbroo:R1 `property : _logical successor_ does not imply any similarity. Is this super-property fitting these two new concepts?

2. The domain and range of `mus:U24` and `mus:U25` are `mus:M24_Track`. What is a concrete example why we should have both in the first place? Next, why don't we use the built-in `rdf:List` which is aimed to represent an ordered list of resources?

Discussion started in #15.

**Comment by pierrechoffe** [comment]
@pasqLisena 
>Next, why don't we use the built-in rdf:List which is aimed to represent an ordered list of resources?

Absolutely, I had forgotten this one... You are right, since what we want to achieve is listing the tracks of an album. So, does this mean that we can leave this out of the ontology?

**Comment by rtroncy** [comment]
Yes, if you want to use a built-in function, you don't need to re-invent the wheel. But you originally wanted to create two different properties (U24 and U25) and now, you want to simply use the semantics of ```rdf:List```? So what were the concrete subtle difference you wanted to capture in the first place?

**Comment by pierrechoffe** [comment]
No difference, I had just forgotten this rdf:List option :smile:

**Comment by rtroncy** [comment]
Resolution: delete the U24 and U25 properties in the ontology.

@pierrechoffe Can you point out in the mapping rules where those would have been used so we can exemplify how RDF list will be used instead in the converter?

**Comment by pierrechoffe** [comment]
This was in the Tracks. So you have track nr 1, track nr 2, etc.
In the case of a multi-CD album, this might be CD nr 1, etc.
We might have other use cases.
I will point to it when we do the mapping.

**Comment by rtroncy** [comment]
I have deleted the U24, U24i, U25 and U25i properties with this commit https://github.com/DOREMUS-ANR/doremus-ontology/commit/d86982a270822e0768f6339db40b96077cf72701.

This means, we have gaps in the numbering of the U properties. Is it a problem for you @pierrechoffe?

**Comment by pierrechoffe** [comment]
@rtroncy no pb, we will fill the gaps :smile:

**Comment by rtroncy** [comment]
Closing this issue then. As soon as the mapping tables for modeling tracks (and their successions in albums) are ready, @pasqLisena will implement them using ```rdf:List``` in the converter.
