### ISSUE TITLE
Missing class on FRBRoo [F50, F38]

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#18]
We added at the [end of the file](https://github.com/DOREMUS-ANR/doremus-ontology/blob/feature/Update2/doremus.ttl#L1207) 2 new properties of efrbroo (`efrbroo:F38_Character` and `efrbroo:F50_Controlled_Access_Point`). But they are currently not in the [efrbroo ontology](http://erlangen-crm.org/efrbroo/F38_Character).

Pierre is going to ask them (opening an issue?).'

Discussion started on #15

**Comment by pierrechoffe** [comment]
Done https://github.com/erlangen-crm/efrbroo/issues/1
the classes are missing in the owl file.

**Comment by pierrechoffe** [comment]
can we close this issue ?

**Comment by rtroncy** [comment]
Clearly not, since the DOREMUS ontology still imports the old version of efrbroo.

**Comment by pasqLisena** [comment]
This become a duplicate of #24
