### ISSUE TITLE
Two different P106 properties in ecrm

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#19]
ecrm contains two properties with code P106: 
- `ecrm:P106_has_component`
- `ecrm:P106_is_composed_of`

We suspect that the latter should be `ecrm:P106i_is_composed_of`.

Pierre is going to open an issue to [erlangen](https://github.com/erlangen-crm/ecrm).

**Comment by pierrechoffe** [comment]
done: https://github.com/erlangen-crm/ecrm/issues/1

**Comment by rtroncy** [comment]
@pasqLisena Can you  study the new [efrbroo version](https://github.com/erlangen-crm/efrbroo/blob/releases/efrbroo_20160715.owl) and, if successful, base DOREMUS on this version? See also [this comment](https://github.com/erlangen-crm/ecrm/issues/1#issuecomment-248580856)

**Comment by pasqLisena** [comment]
Yes, I check it now.

**Comment by pierrechoffe** [comment]
can we close this issue ?

**Comment by rtroncy** [comment]
Clearly not, since the DOREMUS ontology still imports the old version of efrbroo.

**Comment by pierrechoffe** [comment]
There is a new version which you can try out : [efrbroo_20160715.owl](https://github.com/erlangen-crm/efrbroo/blob/releases/efrbroo_20160715.owl)
CIDOC CRM doesn't like constraints, they may want a "weaker" version, without the chain properties, in which case there would be 2 versions, one "strong", one "weak".

**Comment by rtroncy** [comment]
> There is a new version which you can try out : efrbroo_20160715.owl

This is what I wrote in my [comment](https://github.com/DOREMUS-ANR/doremus-ontology/issues/19#issuecomment-248605851)

> CIDOC CRM doesn't like constraints

What does this mean concretely in the OWL/RDF semantics? Adding axioms in OWL/RDF has not for purpose of constraining the usage of classes and properties (since it adopts the Open World assumption) but to enable inferences, i.e. to infer additional types using the axioms

**Comment by pierrechoffe** [comment]
CIDOC CRM prefers a weaker version (yet to be published), so depending on our needs we can use either version.

**Comment by rtroncy** [comment]
I'm coming back to this old issue as defined in https://github.com/DOREMUS-ANR/doremus-ontology/issues/19#issue-176868091 (read also the clarifications in this [github issue](https://github.com/erlangen-crm/ecrm/issues/1)).

The latest version of the efrbroo and ecrm ontologies we are using import / define the properties ```ecrm:P106_is_composed_of``` and ```ecrm:P106i_forms_part_of```. We should use those properties. Furthermore, the property ```ecrm:P148_has_component``` is also defined.

However, ```ecrm:P106_has_component``` **DOES NOT EXIST** and should no longer be used.

@pasqLisena Can you check that this is actually the case in the data, and if so, close the issue?

**Comment by pasqLisena** [comment]
Everything is up-to-date. `ecrm:P106_has_component` is never used, neither in the ontology or in the data.
