### ISSUE TITLE
eFRBRoo update to the 15/07/2017 version

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#24]
A (not-so-much) new version of eFRBRoo is on their [github](https://github.com/erlangen-crm/efrbroo). The release date is 2016-07-15. The file is `efrbroo_20160715.xml`.

Among the new classes (that are not in [our current eFRBRoo version](https://github.com/DOREMUS-ANR/doremus-ontology/blob/master/frbroo.owl)), the class F38_Character.

@delahousse @pierrechoffe Do you see any critical issues in updating it?

**Comment by pierrechoffe** [comment]
No issue at all for me. All the more so as we definitely need F38.

**Comment by delahousse** [comment]
Hello,

I will do the DOREMUS ontology update this week, including this one.

Jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data, Semantic Web, Knowledge
engineering
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

2017-07-25 11:35 GMT+02:00 Pasquale Lisena <notifications@github.com>:

**Comment by pasqLisena** [comment]
Hallo Jean,
I needed it and I already copied the efrbroo file (see commit 2ff5009).
So, update the repo before working on :)

**Comment by delahousse** [comment]
ok
jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data, Semantic Web, Knowledge
engineering
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

2017-08-28 11:59 GMT+02:00 Pasquale Lisena <notifications@github.com>:
