### ISSUE TITLE
Missing M45

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#33]
Is intentional the deletion of M45 in this [commit](https://github.com/DOREMUS-ANR/doremus-ontology/commit/23c8175217248f837894d67ee9cf40bd2239f570#diff-781d9a91a0943ba7c624f100c56b1773L2796)?

If yes, how should it be replaced in the mapping? //cc @ccecconi

**Comment by ccecconi** [comment]
I don't think that's normal. M45 Descriptive Expression Assignment is still in the new classes and properties spreadsheet 
https://docs.google.com/spreadsheets/d/1RNhHnp4fWEhG8G4acx8FPi-nu9fUWNhc8JNf3SQwUFE/edit#gid=317279816

**Comment by rtroncy** [comment]
OK, so it seems to be a class to re-introduce in the ontology by @delahousse
