### ISSUE TITLE
Special character in the fragment identifier of the URI should be avoided

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#4]
Maybe we should avoid using special character in URI.

- `http://data.doremus.org/ontology#M31_Actor&apos;s_Function`
- `http://data.doremus.org/ontology#M32_Actor&apos;s_Responsibility`

https://github.com/DOREMUS-ANR/doremus-ontology/blob/master/Doremus-v0.1.owl#L2083

**Comment by rtroncy** [comment]
+1 I also noticed this yesterday night, basically, you should normalize all fragment id. No apostrophe, no ampersand, replace the white space by an underscore, etc. Remember that the fragment id is NOT the label of the class / property.

**Comment by pasqLisena** [comment]
How can replace it?

1. `M31_Actors_Function`
2. `M31_Actor_s_Function`
3. other way?

**Comment by pierrechoffe** [comment]
`M31_Actor_Function` ?
I was wondering whether we might not as well change the label :+1: 
M31 Actor Function
M32 Actor Responsibility
Are there other special characters in the class or property names?

**Comment by rtroncy** [comment]
@pierrechoffe Are you talking about the label or about the fragment identifier of the class / property ? You seem to give the same value for both, but again, those are two very different things. Look at geonames identifiers. Fragment identifiers are opaque, labels are human readable.

```M31``` represent the class of all possible functions of an actor, right? What is actually interesting is the property ```U31_had_function_of_type```. I would probably propose to delete this class, I don't see its added value. For me, the value of the property ```U31``` is a ```skos:Concept``` that comes from the function concept scheme. Correct?

Actually, I was about to make a similar suggestion, and to delete numerous classes such as ```M4_Key```, ```M5_Genre```, etc. You seem to systematically duplicate the semantics that one can find in the concept scheme already.

**Comment by pierrechoffe** [comment]
> I would probably propose to delete this class

@rtroncy yes, this is sth I was starting to think about... 
we would say:
```
F22 u12_has_genre: "sonate" ; (or URI)
```
So, I will make a list of classes that could be deleted

**Comment by rtroncy** [comment]
No, this is not a string OR a URI. If you do so, this means your property is both a datatype property AND an object property, which means you're making an OWL Full ontology, which is to be avoided.

It depends how you want to formally define the class F22, and for example, if you want to express that F22 is a subclass of an anonymous class that restricts the usage of the property u12 to values that MUST belong to a particular concept scheme. This might be handy just for this purpose to name this class (that generates the restriction). The good modeling pattern to follow here is geonames, that exactly does this.

Before you do or undo anything, let's discuss what precise formalization you aim to apply.

**Comment by pierrechoffe** [comment]
In this case and in most cases I can think of, we will have both possibilities : datatype and object, because we never know the kind of resources the institutions will have.
What should we do ?

**Comment by rtroncy** [comment]
Either I don't understand what you mean or you don't understand what we do in the converter. The whole point of the converter is to automatically and systematically convert "strings" found in MARC to skos concepts for a number of well-defined properties (all the ones which have for value a controlled vocabulary). So I really don't see how you can have both. If you provide a real example, this may explain better what you mean ...

**Comment by pierrechoffe** [comment]
not both: either one or the other.
e.g. (1) BnF using a URI for genre "sonata" (in their AIBM controlled
vocabulary)
and (2) Bibliothèque de Garges-les Gonesses using a string.
We don't know how our users' data is configured and we want to be flexible.
OK, they really should use the controlled vocabulary, but we can also
assume that in some cases a very special genre will not be in the cv, so
this would be another case of using a string rather than URI for the same
class "genre".


2016-06-17 18:31 GMT+02:00 Raphael Troncy <notifications@github.com>:

**Comment by rtroncy** [comment]
So you're really confused :-) We don't modify any original data. When converting data, we make interpretations and choices, that are imposed by the DOREMUS model. In our case, we consider that a genre is a ```skos:Concept``` and not a literal. So we don't have ambiguity anymore. How to always get a  ```skos:Concept``` from the input data is an implementation detail. In our case, this is resolved by the so-called String2URI module. For resolving the problem of never ever complete list of xxx (e.g. genre), the easiest trick is to always have a placeholder misc value.

**Comment by pierrechoffe** [comment]
Things were (relatively) clear for me but this conversation made me confuse... This reminds me of André Gide's quote : "when a philosopher answers me, I don't understand my question anymore" :))
Maybe some examples would help or some "what pb are we trying to solve" kind of approach.
Anyway, I said I would make a list of classes that could be deleted (I will not not delete them myself) and we can talk further.

**Comment by pasqLisena** [comment]
The decision about deleting these classes seems to take time.

In preparation for the turtle conversion #6 , I propose to have `M31_Actor_Function` and `M32_Actor_Responsibility`. We can delete them at a later time.
