### ISSUE TITLE
Defining properties in other namespace than Doremus

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#5]
In Doremus.owl, it seems that we are defining (or redefining?) properties in the frbroo namespace (like [F10_Person](https://github.com/DOREMUS-ANR/doremus-ontology/blob/master/Doremus-v0.1.owl#L2121)) and in the crm one (like [E20_Biological_Object](https://github.com/DOREMUS-ANR/doremus-ontology/blob/master/Doremus-v0.1.owl#L2103)).

Could this be a possible mistake?

**Comment by rtroncy** [comment]
If this happens, this is definitively a mistake. We should import an existing ontology but we should never hijack another namespace for defining or redefining some classes and properties.

**Comment by pierrechoffe** [comment]
I suspect this is because our owl version of FRBRoo is an import from the latest documentation. Could this be the reason ? In any case, when this FRBRoo version will be published by erlangen, the problem should be solved.

**Comment by rtroncy** [comment]
No, this does not seem what @pasqLisena is describing. An OWL import is just one line, disregard what is actually imported. The fact that what is imported will change of status has little to do with the issue described here. I will have a look

**Comment by pasqLisena** [comment]
It seems that actually we do not add any additional information to the original properties/classes (so those lines are simply repetition of ecrm/efrbroo).

**Comment by pierrechoffe** [comment]
sorry, I hadn't looked at the owl file.
Most CRM or FRBRoo properties added are inverse properties, I assume they can be deleted.
Others were created because there was no import of CRM and some classes/properties of DOREMUS are subclasses/subproperties of these (and they are not in FRBRoo either), e.g. E58_Measurement_Unit.
Sometimes also because for whatever reason some FRBRoo classes did not appear in Protégé, e.g. F10_Person.
>An OWL import is just one line, disregard what is actually imported.

True if what you import is clean. That's why I said that when we have a clean version of FRBRoo by erlangen we will not need these anymore, the problem will be solved.

**Comment by pasqLisena** [comment]
> Most CRM or FRBRoo properties added are inverse properties, I assume they can be deleted.

Yes, I think so.

> Others were created because there was no import of CRM.
> Sometimes also because for whatever reason some FRBRoo classes did not appear in Protégé, e.g. F10_Person.

In #6.3, I am suggesting to import directly http://erlangen-crm.org/efrbroo/ (that contains an import to http://erlangen-crm.org/current/ ). I double checked, Protege is visualizing correctly everything with this configuration.

> when we have a clean version of FRBRoo by erlangen

You see critical issues in importing http://erlangen-crm.org/efrbroo/ like in #6  ?

**Comment by rtroncy** [comment]
@pierrechoffe even as interim solution, we should NOT create classes and properties in a namespace we don't control (by doing so, you're breaking the 3rd linked data principle).

**Comment by pierrechoffe** [comment]
>You see critical issues in importing http://erlangen-crm.org/efrbroo/ like in #6 ?

no, we should definitely import it.

>even as interim solution, we should NOT create classes and properties in a namespace we don't control 

Yep, I was a newbie at the time but i'm learning fast (when i have someone to talk to :)  )
