### ISSUE TITLE
Improvements for implementation reasons

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#6]
- [x] **1. Conversion to turtle**

We use turtle for [vocabularies](https://github.com/DOREMUS-ANR/knowledge-base/tree/master/vocabularies) and as output of marc2rdf. I propose to convert also the ontology in turtle (it will be still compatible with Protégé).

- [x] **2. Rename the file "Doremus-v0.1" to "doremus"**
 
The version number could be put inside the file and/or tracked with git tag.

- [x] **3. Reference directly efrbroo from enlargen site**

We [currently](https://github.com/DOREMUS-ANR/doremus-ontology/blob/master/Doremus-v0.1.owl#L19) import FRBRoo from our [local version](https://raw.githubusercontent.com/DOREMUS-ANR/doremus-ontology/master/FRBRoo-v2.4-Biblissima-2016-04-17.owl). We can simply have
`<owl:imports rdf:resource="http://erlangen-crm.org/efrbroo/"/>`

**Comment by rtroncy** [comment]
+1 for all three suggestions. I would even lowercase the filename into ```doremus```. We should offer multiple syntax for the ontology (rdf/xml, turtle, and owl/xml among others)

**Comment by pasqLisena** [comment]
> I would even lowercase the filename into doremus.

I agree, post updated.

> We should offer multiple syntax for the ontology (rdf/xml, turtle, and owl/xml among others)

So, your proposal is to have in this repo the 3 files?

**Comment by rtroncy** [comment]
> So, your proposal is to have in this repo the 3 files?

No, we can just pick one for the working version and turtle is indeed more human readable, so +1. When we will publish the ontology, we can generate multiple serializations.
