### ISSUE TITLE
Useful RDF properties to add

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/doremus-ontology#7]
I propose to add these RDF properties.

On the **ontology** node:

- [ ] `dc:description "Doremus is an extension of the FRBRoo model for describing the music." ;`
- [ ] `vann:preferredNamespacePrefix "mus" ;`
- [ ] `vann:preferredNamespaceUri "http://data.doremus.com/ontology#" ;`
- [ ] `owl:versionInfo "Version: 0.1" ;`

On each **class and property**
- [ ] `rdfs:isDefinedBy mus: ;`

**Comment by rtroncy** [comment]
+1 for the metadata to attach to the ontology. We may argue for the version number though :-)

+1 as well for adding ```rdfs:isDefinedBy``` statements to the classes and properties, which will please Virtuoso folks, but the value should be ```<http://data.doremus.com/ontology#>``` and not ```mus:```, right?

**Comment by pasqLisena** [comment]
> We may argue for the version number though :-)

Well, it will start to make more sense since 1.0.
Before it could be a mark for us.

> but the value should be <http://data.doremus.com/ontology#> and not mus:, right?

I think it is better indeed. I tell you, I took inspiration from [3cixty ontology](https://github.com/3cixty/knowledgebase/blob/master/ontology/3cixty.ttl#L29).

**Comment by rtroncy** [comment]
> I took inspiration from 3cixty ontology.

I really need to improve it!

**Comment by rtroncy** [comment]
Out of curiosity, did you add the set of ```rdfs:definedBy``` statements via a script? Would those be preserved when re-editing the ontology on Protégé?

**Comment by pasqLisena** [comment]
> Out of curiosity, did you add the set of rdfs:definedBy statements via a script?

No, regex on a text editor.

> Would those be preserved when re-editing the ontology on Protégé?

Yes, they are properties like others. But I do not know if we do something different (example: generating the ontology form an excel).
