### ISSUE TITLE
Generate a proper HTML documentation of the DOREMUS ontology

### ISSUE THREAD

**Issue by rtroncy** [DOREMUS-ANR/doremus-ontology#9]
There are various tools that enable to automatically generate an HTML documentation out of a OWL ontology. For example:
- owldoc: https://github.com/co-ode-owl-plugins/owldoc ... a Protégé plugin that generates a bundle of HTML pages like Javadoc;
- specgen: https://github.com/specgen/specgen ... written in Python, the [version 5 on svn](http://svn.foaf-project.org/foaftown/specgen/) was used to generate the [FOAF ontology](http://xmlns.com/foaf/spec/) documentation among others. The version 6 enables to embed RDFa (see this [blog post](https://smiy.wordpress.com/2010/07/13/my-specgen-version-6/))
- ontospec: http://moustaki.org/resources/onto_spec.pl ... written in Prolog, was used to generate the [Music Ontology](http://purl.org/ontology/mo/) documentation

Other visualization tools include:
- The LODE service: https://github.com/essepuntato/LODE 
- The Parrot service: http://ontorule-project.eu/parrot/parrot
- The webvowl service: http://vowl.visualdataweb.org/webvowl.html

**Comment by pasqLisena** [comment]
For a personal preference, and because our ontology contains hashes `#`, I think is better an one-page documentation. I am going to try specgen and ontospec and I will choose among these two.

**Comment by rtroncy** [comment]
I even have a preference for specgen, either forking the v5 or the v6. I should remember the improvements we talked about in the group some years ago. This will require doing some archeology in my computer :-)

**Comment by pasqLisena** [comment]
The documentation for the Ontology is currently:
- available at http://data.doremus.org/ontology/
- under further development in the project [OWL Coat](https://github.com/DOREMUS-ANR/OWL-Coat)

Future requests for the evolution of the documentation can be described in new issues
